name: Release distributable MCPB

on:
  push:
    tags:
      - 'v*'

jobs:
  release-mcpb:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for upload artifacts

    steps:
      - uses: actions/checkout@v6

      - name: Verify version consistency
        run: |
          TAG_VER="${GITHUB_REF_NAME#v}"
          MST_VER="$(jq -r '.version' manifest.json)"
          PKG_VER="$(jq -r '.version' package.json)"

          if [ "$TAG_VER" != "$MST_VER" ]; then
            echo "❌ Version mismatch between tag ($TAG_VER) and manifest ($MST_VER)"
            exit 1
          elif [ "$TAG_VER" != "$PKG_VER" ]; then
            echo "❌ Version mismatch between tag ($TAG_VER) and package ($PKG_VER)"
            exit 1
          else
            echo "✅ Version ($TAG_VER) is consistent across tag, manifest, and package"
          fi

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - run: npm ci

      - run: npm run pack

      # upload MCPB extension to the GitHub release
      - uses: softprops/action-gh-release@v2
        with:
          files: cdt-express.mcpb
          generate_release_notes: true
          append_body: false
